# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-camcalibration-dep
  labels:
    app: {{ .Release.Name }}-camcalibration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-camcalibration
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-camcalibration
    spec:
      shareProcessNamespace: true
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      initContainers:
        - name: wait-for-web-initcontainer
          image: busybox
          command: ["/bin/sh", "-c", "until wget -q --spider http://web.{{ .Release.Namespace }}.svc.cluster.local; do sleep 1; done"]
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            {{ include "defaultContainerSecurityContext" . | indent 12 }}
        - name: fix-permissions-initcontainer
          image: busybox
          command: ["/bin/sh", "-c", "chown -R 1000:1000 /data/media /data/datasets && echo 'Permissions fixed'"]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
          - mountPath: /data/media
            name: media-storage
          - mountPath: /data/datasets
            name: datasets-storage
      containers:
        - args:
          - --restauth
          - /run/secrets/calibration.auth
          - --resturl
          - https://web.{{ .Release.Namespace }}.svc.cluster.local/api/v1
          - --brokerauth
          - /run/secrets/calibration.auth
          - --broker
          - broker.{{ .Release.Namespace }}.svc.cluster.local
          image: {{ .Values.repository }}/{{ .Values.camcalibration.image }}:{{ .Chart.AppVersion }}
          name: {{ .Release.Name }}-camcalibration
          env:
          - name: EGL_PLATFORM
            value: surfaceless
          - name: NETVLAD_MODEL_DIR
            value: /usr/local/lib/python3.10/dist-packages/third_party/netvlad
          {{ include "proxy_envs" . | indent 10 }}
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            periodSeconds: 1
          resources: {}
          volumeMounts:
          - mountPath: /run/secrets/certs
            name: certs
            readOnly: true
          - mountPath: /run/secrets/django
            name: django
            readOnly: true
          - mountPath: /run/secrets/calibration.auth
            name: calibration-auth
            readOnly: true
            subPath: calibration.auth
          - mountPath: /home/scenescape/SceneScape/media
            name: media-storage
          - mountPath: /home/scenescape/SceneScape/datasets
            name: datasets-storage
      restartPolicy: Always
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: certs
        secret:
          secretName: {{ .Release.Name }}-certs
      - name: django
        secret:
          secretName: {{ .Release.Name }}-django
      - name: calibration-auth
        secret:
          secretName: {{ .Release.Name }}-calibration.auth
      - name: media-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-media-pvc
      - name: datasets-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-datasets-pvc
status: {}
